import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Tamahomechi",
    short_name: "Tamahomechi",
    description: "El Tamagotchi de tu hogar",
    start_url: "/hoy",
    display: "standalone",
    background_color: "#f7f2eb",
    theme_color: "#c06a3e",
    orientation: "portrait",
    icons: [
      // Rasterized PNGs generated by app/icon.tsx and app/apple-icon.tsx.
      // Explicit sizes help Android pick the right asset for adaptive
      // icons, and the distinct URLs ensure devices that cached the
      // previous icon see fresh entries after a redeploy.
      {
        src: "/icon?v=2",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon?v=2",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/apple-icon?v=2",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
      // Vector fallback — scales perfectly on browsers that prefer SVG.
      {
        src: "/logo.svg?v=2",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
    ],
  };
}
